### ISSUE TITLE
ExecTargetAfterPublish does not work for publish method File System

### ISSUE THREAD

**Issue by deerchao** [sayedihashimi/publish-samples#2]
Neither AfterPackage nor AfterPublish works when publish method set to File System.

Is there anything I can do about that?

**Comment by sayedihashimi** [comment]
Are you publishing from within VS or the command line? If from VS unfortunately File System has a limitation here. The best thing to do is to open an issue at http://aspnet.uservoice.com and up vote it.

It should work from the command line though.

I'll close this item, but if your issue relates to command line please reactive it so that I can take a look.
